### ISSUE TITLE
Add Friend Requests

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#101]
## Value proposition
As a user
I want to see all my friend requests fo real app user accounts
In order to accept or deny these requests
## Description
There should be a functionality in order to display friend requests by real app users. There should be a the opportunity to deny or accept a friend request.

## Acceptance criteria
- [ ] user should see all friend requests by app users on the profile page
- [ ] user should be able to accept or deny the requests
- [ ] user should see the change in the actual friend list if the request has been accepted
## Tasks
- [ ] Impelement the logic for displaying a new friend request in the proper user profile page
- [ ] Create a new button in order to accept a friend request
- [ ] Implement the logic to deny a friend request to the already existing deny button

**Comment by justincaze** [comment]
lgtm
