### ISSUE TITLE
add author and dato to activityCard

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#103]
## Value proposition
As a user
I want to hafe some more details on this card
In order to not have to open the detailCard
## Acceptance criteria
- [ ] The author shold be visible on the card
- [ ] If the date is less than a week away, the day of the week should be displayed instead
- [ ] If it is today or tomorrow, this should be displayed instead
## Tasks
- [ ] Create a function to display the author by using his ID
- [ ] Create a function to find how many days in the future each activity is
- [ ] If an activity is more than one and less than seven days away, get its day of the week an display it on the card instead of the date
- [ ] If an activity is tomorrow, display "tomorrow"
- [ ] If an activity is today, display "today"
