### ISSUE TITLE
User Story 6 - Join Feature

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#12]
## Value proposition
As a user
I want to click on a "Join" button on the Details Page of an activity
In order to save the activities I want to participate in
## Description
![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/138215839/1c6ad7b9-586d-4573-b45c-55f0a764e588)

## Acceptance criteria
- [ ] The Detail Page should have a join button
- [ ] Users should be able to access the join functionality for activities on the Detail Page
- [ ] Join button should change visually after click in order to see a confirmation
- [ ] Users should be able to disjoin the activity

## Tasks
- [ ] Create a Join button on the Details Page
- [ ] Create a function that sets the boolean value of an activity object to true/false in the mongoDB
- [ ] Add a boolean to the activity Scheme
- [ ] Add a toggle functionality to the Join button

**Comment by MerleMak** [comment]
maybe you can create a counter for the amount of people that are joining? :) 
Like a little tag "15 people are participating" :)
