### ISSUE TITLE
User Story 7 - Joined Page

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#13]
## Value proposition
As a user
I want to have access to a Joined Page
In order to see all my joined  #activities
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/138215839/5ff12387-cb1f-437b-a55e-2c96cd0cc366)

## Acceptance criteria
- [ ] Users should be able to access a separate page with the headline "Joined"
- [ ] On the Joined Page there should be an overview about the joined activities
- [ ] Users should be able to go back to the overview page
## Tasks
- [ ] Create a page that renders the activity cards that have the boolean "true", a headline "Joined" and a "back" button
- [ ] Create a Link that redirects the user to the overview page
