### ISSUE TITLE
Create App Styling

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#15]
## Value proposition
As a user
I want to have equal styling proportions on each Page and a general color scheme on each Page
In order to have an intuitive overall orientation within the app and to avoid confusion through too many different styles and colors that doesn't match
## Acceptance criteria
- [ ] Equal spacing between same elements on the proper pages
- [ ] Equal colors on proper elements (buttons, captions..)
- [ ] Equal font styling on each page
## Tasks
- [ ] Define a color scheme for the app
- [ ] Define proper spacing for the elements
- [ ] Define spacing for different screen sizes (desktop, smartphone..)
