### ISSUE TITLE
Edit Form - show current text

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#16]
## Value proposition
As a user
I want to be able to see what's currently inside the textfield
In order to only change, what is needed
## Description
![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/be534cf9-6def-47db-9f38-871beb6bc892)

## Acceptance criteria
- [ ] If the textfield was empty before, show the empty field as in the create activity page
- [ ] If the user cancels, nothing really changes and it look's like before 
- [ ] If I only change one textfield input, the others should stay as they are
## Tasks
- [ ] somethingsomething
