### ISSUE TITLE
Activity Calendar

### ISSUE THREAD

**Issue by d-hung-nguyen** [alex96dev/Easy-Meetup-with-Friends#17]
## Value proposition
- As a user of the social platform,
- I want to access an activity calendar via a swipeable gallery on the homepage,
- In order to easily manage and view my activities in an organized and interactive manner
## Description
- The activity calendar is accessible as part of a swipeable gallery on the home page, specifically located in the 3rd swipe window. 
- This swipe window features a calendar view at the top, displaying the current month with ability to swipe or navigate to view past or future months. 
- Below the calendar, summaries of selected activities are displayed. If a day with planned activities is tapped or clicked on the calendar, a summary of those activities appears below. 
- The menu bar of the calendar window includers three options: a filter to refine which activities are displayed based on criteria (e.g., category, date rage...), an activity status icon indicating the completion status or upcoming status of activities and a button to create new activities.  
<img width="355" alt="Screenshot 2024-03-08 at 09 50 33" src="https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155955471/3f013304-6a7a-4cc0-b439-adebf56e6f7a">

## Acceptance criteria
- [ ] Ensure the swipeable gallery seamlessly transitions between the three swipes. 
- [ ] Implement the calendar view at the top half of the window, allowing user to switch between months and displaying days with planned activities distinctly. 
- [ ] Enable displaying a summary of activities for a selected day immediately below the calendar. If no activities are planned for the selected day, provide a text to encourage the user to create a new activity. 
- [ ] The menu bar should feature options for filtering activities, displaying activity status, and creating new activities, ensuring each function is accessible and intuitive to use.
- [ ] Confirm the functionality for adding, viewing, editing, and deleting activities through the calendar window operates correctly and updates are reflected in real-time (**be reviewed with team**)
## Tasks
 - [ ]  Design the UI layout for the swipeable gallery on the homepage, with the activity calendar located in the 3rd swipe window.
 - [ ] Implement the calendar view with functionality to highlight days with activities and navigate between months.
 - [ ] Develop the UI for displaying activity summaries below the calendar view when a day is selected.
 - [ ] Create and integrate menu bar options for filtering activities, showing activity status, and adding new activities within the calendar window.
 - [ ] Conduct testing to ensure the calendar window and its functionalities meet the specified acceptance criteria.
