### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#18]
## Value proposition
As a user
I want to use and see a navigation bar on each page
In order to navigate easyly between pages by swiping
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/138215839/6a708508-b1f1-4843-b4e2-b0e4eb1609d4)

## Acceptance criteria
- [ ] Slider should represent dots for each page in order to see how many previous/further pages the user can reach
- [ ] User should be able so swipe between pages on touchscreens
- [ ] User should be able to click on a dot to access a previous/further page
## Tasks
- [ ] Create swipe bar/dot buttons that listens to swipes(for touchscreens) and clicks(for desktops) by users
- [ ] Create a function that redirects the user to the previous/further page
- [ ] Implement an animation for the transition while users switching pages
