### ISSUE TITLE
Enhance the Calendar Page with Stashes and MongoDB Integration

### ISSUE THREAD

**Issue by d-hung-nguyen** [alex96dev/Easy-Meetup-with-Friends#25]
## Value proposition
As a user of the application,

I want the calendar page to display two stashes below the calendar, each with a distinct color format, and to highlight today's date in a different color, with a dedicated button to quickly navigate to today's date,

So that I can easily distinguish between different types of activities and quickly identify and access today's activities.

## Description:

Enhance the existing activity calendar: addition of two distinct stashes below the calendar for better activity differentiation, a unique color highlight for today's date and transitioning the calendar's data source to a MongoDB database. These features aim to provide users with a more intuitive and efficient way to identify and access their activities and events.
<img width="350" alt="image" src="https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155955471/58af60b2-5bd0-4c72-92b7-596d37805541">

## Acceptance Criteria:

-[] Two Distinct Stashes Below the Calendar:
(1) There should be two stashes displayed below the calendar.
(2) Each stash must have a unique color format to differentiate between two types of activities or events.
- [] Highlight Today's Date:
Today's date should be highlighted on the calendar with a unique color that distinguishes it from other dates.
-[] Database Integration with MongoDB:
- [] The calendar's data source should be switched from the current local ./lib/activity to a MongoDB database.
This change requires updating the backend to fetch calendar data from MongoDB, ensuring that activities and events are persistently stored and retrieved from the database.

## Tasks

- [] Implement for the two stashes with distinct color coding.
- [] Create a visual highlight for today's date on the calendar.
- [] Backend Integration:
Set up a MongoDB database and configure it to store and retrieve calendar activities.
Update backend services to fetch activity data from MongoDB instead of the static ./lib/activity file.
