### ISSUE TITLE
Details Page Styling

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#27]
## Value proposition
As a user
I want to have a proper styling on the Details Page equivalent to the other pages
In order to have an intuitive user experience and good orientation
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/138215839/94541eb1-8e89-42d9-8adf-cda607725d3c)

## Acceptance criteria
- [ ] Use Color scheme as defined in user story "Global App Styling"
- [ ] Use Font sizes and spacing as defined in user story "Global App Styling"
- [ ] Use Box styling as defined in user story "Global App Styling"
## Tasks
- [ ] Implement the styles as mentioned in acceptance criteria in the proper styled components
- [ ] Add a Headline at the top called "Join your friend!"
- [ ] Create border boxes for activity name, activity details
- [ ] If necessary refactor or create new styled components
