### ISSUE TITLE
User Story 2 - Detail Page

### ISSUE THREAD

**Issue by stellanw** [alex96dev/Easy-Meetup-with-Friends#3]
## Value proposition
As a User
I want to see details about the activity I'm interested in,
in order to choose one by getting more information about it.

## Description
Display comprehensive details of each activity, including creator-name, activity-name, weekday, date, time, location, category, description and tags. Ensure the information is presented in a clear and organized manner for easy comprehension.

## Acceptance criteria

 
 
 If an activity lacks certain details (e.g., description, tags), display placeholder text or indicate the absence of information.
 Ensure the layout and design are visually appealing and user-friendly.

- [ ] When viewing activity details, all fields should be populated with accurate information.
- [ ] Clicking on an ActivityCard at the overview, navigates the user to its detailed view.
- [ ]  If an activity lacks certain details (e.g., description, tags), display placeholder text or indicate the absence of information.
- [ ] Ensure the layout and design are visually appealing and user-friendly.
- [ ] If informations didn't fetched, the user should see an error message.

## Tasks
- [ ] Create a new ActivityDetails component.
- [ ] Implement logic to fetch activity details from the database.
- [ ] Handle cases where certain details may be missing or incomplete.

**Comment by NikRoe** [comment]
Hi there,

this looks promising!

I have two questions:

- How can a user navigate back from the detail view to the homepage? Does clicking on "close" trigger this? If that is the case, please describe this behaviour in your Acceptance Criteria

- In your Tasks you mention a fetch from the database. However, in your previous User Story you fetch the data from an external API and display it. Why does this User Story not also fetch the data from that API?

✌️
