### ISSUE TITLE
Final App Styling

### ISSUE THREAD

**Issue by alex96dev** [alex96dev/Easy-Meetup-with-Friends#35]
## Value proposition
As a developer
I want to optimize the styling of all pages
In order to get a final app styling
##  Description
-  Optimizing and adding styles to get a final App styling leads to a general glow up regarding the user experience.

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/138215839/99b7e594-2aa2-41a8-b6a7-0c6224159f0a)

## Acceptance criteria
- [ ] Users should be limited in the amount of letters they can use for the Activity Name
- [ ] Users should see the date and time of the Activity Cards on the Homepage in a fluent way with equal positioning for each Activity Card
- [ ] The Joined Mark should get more contrast to the Activity Name by changing the position
- [ ] Users should get a responsive Design of the App: Activity Cards should be wider if the screen size gets bigger and crosses a fix breakpoint. Same for the elements in the navbar.
- [ ] Users should see a marker between Activity Name and date/time in order to see a clear cut between these to elements of the Activity Card

## Tasks
- [ ] Set a maximum amount of letters as Activity Name
- [ ] Set date and time position on the right side with a fixed spacing to the right side ActivityCard border
- [ ] Place the Joined Mark closer to top left corner within the ActivityCard
- [ ] Set breakpoints for the desktop design and the mobile display as well
- [ ] Display a Bar between Activity Name and date/time
