### ISSUE TITLE
create login page

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#36]
## Value proposition
As a user 
I want to be able to log in 
In order to enter the website
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] Should be the first Page to enter
- [ ] Should be the only way to enter the website
- [ ] No way of creating an account, works only via github account
- [ ] Should contain a button to sign in
## Tasks
- [ ] Create log in page whit button
- [ ]
