### ISSUE TITLE
Hide expired Activitycards

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#37]
## Value proposition
As a user
I want to only see upcoming activities
In order to keep an overview
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] If a activity expired, it should not be rendered
- [ ] It should not be possible, to set a past day or time to an activity 
## Tasks
- [ ] Create function to check if the current date and time are past the ones of each activity
- [ ] If an activity expired, delete it.
- [ ] find a way to make it impossible for the user to select a past day or time
