### ISSUE TITLE
Sort cards by date

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#41]
## Value proposition
As a user
I want to see all upcoming activities sorted by date an time
In order to keep track and navigate quickly 
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/ca76c6cc-0e5f-469e-97ad-37802130652c)

## Acceptance criteria
- [ ] The activity, closest to the current day and time should be the first/ on top
- [ ] The second activity should bo on the second spot and so on, ...
- [ ] If a new activity was created, it should pop up on the right spot
- [ ] If a activity was edited and the time or date was changed it should pop up on the right spot
- [ ] if there are more than one activity on one day, the should be sorted by time 
## Tasks
- [ ] Create a function to map over all activities to get day and time
- [ ] Sort them by date and time
