### ISSUE TITLE
Calendar styling

### ISSUE THREAD

**Issue by stellanw** [alex96dev/Easy-Meetup-with-Friends#42]
## Value proposition
As a user,
I want to see an organized calendar page that fits the app's overall design
In order to easily view and manage scheduled activities.

## Description
Design the calendar page with a clean layout and consistent design elements.
Ensure the calendar integrates seamlessly with the app's existing aesthetic.

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155980451/6e03499b-a09d-4c17-9aa0-80e6b38d3c14)

## Acceptance criteria
- [ ] Style the calendar, the calendar page layout and the displayed activity cards, so that it fits to the overall App design.
- [ ] Clicking on a specific date should display any scheduled activities for that date.
- [ ] If there are no activities scheduled for a date, display a message indicating no events.
- [ ] If there is an error fetching calendar data, display an alert with the text "Failed to retrieve calendar data. Please try again later."

## Tasks
- [ ] Style the layout and style of the calendar page.
- [ ] Integrate the calendar with the app's design system by using the theming method and global styles.
- [ ] Implement logic for retrieving and displaying scheduled activities on the calendar.
- [ ] Implement logic for retrieving and displaying activity cards by clicking on a calendars day field.
- [ ]  Implement error handling for failed calendar data retrieval.
