### ISSUE TITLE
add friendList

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#43]
## Value proposition
As a user
I want to only see the activities of my friends
In order to only join theirs
## Acceptance criteria
- [ ] If the user is friends with someone, the user should get all his activities 
- [ ] If the user is friends with someone, the friend should get all of the users activities 
- [ ] None of a strangers activities should be displayed in the users version
- [ ] None of the users activities should be displayed in the version of a stranger
## Tasks
- [ ] Create some dummy users
- [ ] Create a friendList an add some of them to the list 
- [ ] Create a function that checks which activities where created by your friends
- [ ] Add some code to the activitiyCardSection to only display those
