### ISSUE TITLE
Style joinedPage

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#48]
## Value proposition
As a developer
I want to optimize the styling of all pages
In order to get a final app styling
##  Description
-  Optimizing and adding styles to get a final App styling leads to a general glow up regarding the user experience.

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/ac19722a-11a6-4673-aafe-e253b3ce80e3)

## Acceptance criteria
- [x] It should look just like the mainPage without the mainPage features
- [ ] Users should get a responsive Design of the App: Activity Cards should be wider if the screen size gets bigger and crosses a fix breakpoint. Same for the elements in the navbar.

## Tasks
- [x] Style this Page exactly the way the mainPage was styled
- [ ] Make it responsive
