### ISSUE TITLE
calendar - add all functions

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#49]
## Value proposition
As a user
I want to see all upcoming activities in a calendar
In order to get a better overview
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/2278a1ca-70af-4bf2-b70a-642dc2de8015)

## Acceptance criterion
- [ ] Mark all days when an activity takes place
- [ ] All markers should be the same color as the activity they belong to
- [ ] If more than one activity takes place in a day, two points should be awarded, but never more than two
- [ ] Clicking on a day should display all activity cards associated with that day below the calendar
## Tasks
- [ ] Create a function that checks which day an activity is assigned to and displays it in the correct place on the calendar
- [ ] Create some sort of marker just to see if it works (styling will be another story)
- [ ] Display the marker in the color of its activity
- [ ] Make the marker clickable and show the associated activities below the calendar
