### ISSUE TITLE
Refactoring Navigation

### ISSUE THREAD

**Issue by stellanw** [alex96dev/Easy-Meetup-with-Friends#57]
## Value proposition
As a user
I want to navigate intuitively
In order to use the app intuitively

## Description
The user should use a dynamic navigation which changed dynamically depending on which page he is.

## Acceptance criteria
- [ ] The User can create activities by clicking the create button in navigation from the pages "/" "joined" and "calendar"
- [ ] The User should be lead back to current page while clicking on the back button when on Details Page

## Tasks
- [ ] Lifting up UseStates to _app.js 
- [ ] Add dynamic to Details Page back Button

**Comment by MerleMak** [comment]
I think you mean intuitively :D

**Comment by alex96dev** [comment]
LGTM!
