### ISSUE TITLE
Add userProfile

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#60]
## Value proposition
As a user 
I want to have my profile
In order to see my name and picture
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/cf617ff0-c83e-4c22-afcd-50fb8078f845)

## Acceptance criteria
- [ ] The head of the friedlist should be the users profile
- [ ] It should contain the user name and picture
- [ ] It should contain a searchbar to add find new friends (not functional)
- [ ] It should contain a button to open friend requests (not functional)
## Tasks
- [ ] Create the profile component
- [ ] Add a searchbar and a button

**Comment by F-Kirchhoff** [comment]
Hey Timur,
please don't include ui elements that are not functional yet. You can add them later with the respective feature.

**Comment by F-Kirchhoff** [comment]
Please add more detail to your task list, describe the steps needed to create the profile in more detail.

**Comment by F-Kirchhoff** [comment]
Hey Timur,
this looks good now. 🚀
