### ISSUE TITLE
Add window for friend requests

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#68]
## Value proposition
As a user
I want to be able toe see, who wants to be friends with me
In order to confirm or delete them
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/1947d75a-1af3-4d05-8aa9-e1f3b465206f)

## Acceptance criterion
- [ ] Should only be visible when the button is clicked
- [ ] Shows all requests
- [ ] Opens like the filter (with an animation)
- [ ] When the delete button is clicked, this request should disappear from the list
## Tasks
- [ ] Create the friendRequest component.
- [ ] Add a button to the friends list to open the component
- [ ] The component remains hidden until the button is clicked
- [ ] Create dummy requests and render them within the component
- [ ] Add a delete button to each request
- [ ] Make sure the delete button deletes the request

**Comment by stellanw** [comment]
God Job!
