### ISSUE TITLE
Add searchbar to find new friends

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#69]
## Value proposition
As a user
I want to be able to search for new friends
In order to add them to my friendlist
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/4475939b-7ca1-4574-9f2c-37373b3ba74b)

## Acceptance criteria
- [ ] 
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team

**Comment by stellanw** [comment]
Great!
