### ISSUE TITLE
Fetch real data

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#70]
## Value Proposition
As a developer
I want to replace all dummy data with real data
in order to complete functionality
## Acceptance criteria
- [ ] All dummy users should be taken out of the code
- [ ] All functions should work as before 

## Tasks
- [ ] Delete all dummy users in all components (friendList, friendRequest, findFriend)
- [ ] Map over all users and only show each user's friends in their friends list
- [ ] Change the search function to map over all existing users and show the results dynamically
- [ ] Change the friend request so that it works with the real data and real requests are shown

**Comment by stellanw** [comment]
Looks good!
