### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by stellanw** [alex96dev/Easy-Meetup-with-Friends#74]
## Value proposition
As a user browsing activity cards,
I want to see a bookmark icon indicating my participation,
In order to easily identify the activities I have joined.

## Description
Add a bookmark "icon" to the activity cards that the user has joined.
Replace the "xx" string with "joined" to indicate user participation.

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155980451/c152dc63-5a61-4f42-94e9-8afeef1e8c42)

## Acceptance criteria

- [ ] When the user hasn't joined an activity, no bookmark icon should be displayed.
- [ ] Clicking on the "Join" Button on Details Page should toggle the user's participation status.

## Tasks
- [ ] Add bookmark icon to activity cards.

**Comment by alex96dev** [comment]
LGTM!
