### ISSUE TITLE
Upcoming activity

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#79]
## Value proposition
As a user
I want to see my next upcoming activity
In order to know which one is next
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/31408285-1c0c-4a7e-8679-1faf33448ce9)

## Acceptance criterion
- [ ] The next upcoming activity means that it is the next one in time and it must be joined
- [ ] The next upcoming activity should be displayed on the main page above all activities and below the weather
- [ ] Above this is the text as shown in the wireframe
- [ ] It looks like all other cards
- [ ] There should be a thin line and twice the distance between this activity and the others below
- [ ] If I haven't joined one, all activity is directly below the weather, the line and its gap remain between the two
## Tasks
- [ ] Create the NextUpcomingActivity component
- [ ] Use the Find method to locate and return the next upcoming activity
- [ ] If you don't have a connected activity, don't display anything except the thin line
- [ ] Make it so that when you click on it and disjoin on the details page, the next card will be displayed when you return to the main page
