### ISSUE TITLE
Add a history

### ISSUE THREAD

**Issue by justincaze** [alex96dev/Easy-Meetup-with-Friends#82]
## Value proposition
As a user
I want to see my history
In order to know what a already did
## Description

![Image](https://github.com/alex96dev/Easy-Meetup-with-Friends/assets/155940239/0f991ada-1180-4062-8e4d-1ee54653d03b)

## Acceptance criteria
- [ ] The user's joined page should display their history
- [ ] It appears directly below all upcoming activities and is separated by a thin line and text above it, as shown in the wireframe
- [ ] The sorting is reversed so that the last Activity is at the top. So when you scroll down, the further into the past you go
## Tasks
- [ ] Create the JoinedHistory component
- [ ] Map over all joined activities and separate them by date and time (Future: today to future, Past: today to past)
- [ ] Display the “Future” as before and add the component below it
- [ ] Swap the order of the “Past” so that the further you scroll, the further into the past you go
